/* automatically generated by rust-bindgen 0.72.0 and slightly edited */

pub const LIBSAIS16_VERSION_MAJOR: u32 = 2;
pub const LIBSAIS16_VERSION_MINOR: u32 = 10;
pub const LIBSAIS16_VERSION_PATCH: u32 = 2;
pub const LIBSAIS16_VERSION_STRING: &str = "2.10.2";

unsafe extern "C" {
    /// Creates the libsais16 context that allows reusing allocated memory with each libsais16 operation.In multi-threaded environments, use one context per thread for parallel executions.
    ///
    /// # Returns
    ///
    /// the libsais16 context, NULL otherwise.
    pub fn libsais16_create_ctx() -> *mut ::std::os::raw::c_void;

    /// Creates the libsais16 context that allows reusing allocated memory with each parallel libsais16 operation using OpenMP.In multi-threaded environments, use one context per thread for parallel executions.
    ///
    /// # Arguments
    ///
    /// * `threads` - The number of OpenMP threads to use (can be 0 for OpenMP default).
    ///
    /// # Returns
    ///
    /// the libsais16 context, NULL otherwise.
    #[cfg(feature = "openmp")]
    pub fn libsais16_create_ctx_omp(threads: i32) -> *mut ::std::os::raw::c_void;

    /// Destroys the libsass context and free previusly allocated memory.
    ///
    /// # Arguments
    ///
    /// * `ctx` - The libsais16 context (can be NULL).
    pub fn libsais16_free_ctx(ctx: *mut ::std::os::raw::c_void);

    /// Constructs the suffix array of a given 16-bit string.
    ///
    /// # Arguments
    ///
    /// * `T` - [0..n-1] The input 16-bit string.
    /// * `SA` - [0..n-1+fs] The output array of suffixes.
    /// * `n` - The length of the given 16-bit string.
    /// * `fs` - The extra space available at the end of SA array (0 should be enough for most cases).
    /// * `freq` - [0..65535] The output 16-bit symbol frequency table (can be NULL).
    ///
    /// # Returns
    ///
    /// 0 if no error occurred, -1 or -2 otherwise.
    pub fn libsais16(T: *const u16, SA: *mut i32, n: i32, fs: i32, freq: *mut i32) -> i32;

    /// Constructs the generalized suffix array (GSA) of given 16-bit string set.
    ///
    /// # Arguments
    ///
    /// * `T` - [0..n-1] The input 16-bit string set using 0 as separators (T[n-1] must be 0).
    /// * `SA` - [0..n-1+fs] The output array of suffixes.
    /// * `n` - The length of the given 16-bit string set.
    /// * `fs` - The extra space available at the end of SA array (0 should be enough for most cases).
    /// * `freq` - [0..65535] The output 16-bit symbol frequency table (can be NULL).
    ///
    /// # Returns
    ///
    /// 0 if no error occurred, -1 or -2 otherwise.
    pub fn libsais16_gsa(T: *const u16, SA: *mut i32, n: i32, fs: i32, freq: *mut i32) -> i32;

    /// Constructs the suffix array of a given integer array.Note, during construction input array will be modified, but restored at the end if no errors occurred.
    ///
    /// # Arguments
    ///
    /// * `T` - [0..n-1] The input integer array.
    /// * `SA` - [0..n-1+fs] The output array of suffixes.
    /// * `n` - The length of the integer array.
    /// * `k` - The alphabet size of the input integer array.
    /// * `fs` - Extra space available at the end of SA array (can be 0, but 4k or better 6k is recommended for optimal performance).
    ///
    /// # Returns
    ///
    /// 0 if no error occurred, -1 or -2 otherwise.
    pub fn libsais16_int(T: *mut i32, SA: *mut i32, n: i32, k: i32, fs: i32) -> i32;

    /// Constructs the suffix array of a given 16-bit string using libsais16 context.
    ///
    /// # Arguments
    ///
    /// * `ctx` - The libsais16 context.
    /// * `T` - [0..n-1] The input 16-bit string.
    /// * `SA` - [0..n-1+fs] The output array of suffixes.
    /// * `n` - The length of the given 16-bit string.
    /// * `fs` - The extra space available at the end of SA array (0 should be enough for most cases).
    /// * `freq` - [0..65535] The output 16-bit symbol frequency table (can be NULL).
    ///
    /// # Returns
    ///
    /// 0 if no error occurred, -1 or -2 otherwise.
    pub fn libsais16_ctx(
        ctx: *const ::std::os::raw::c_void,
        T: *const u16,
        SA: *mut i32,
        n: i32,
        fs: i32,
        freq: *mut i32,
    ) -> i32;

    /// Constructs the generalized suffix array (GSA) of given 16-bit string set using libsais16 context.
    ///
    /// # Arguments
    ///
    /// * `ctx` - The libsais16 context.
    /// * `T` - [0..n-1] The input 16-bit string set using 0 as separators (T[n-1] must be 0).
    /// * `SA` - [0..n-1+fs] The output array of suffixes.
    /// * `n` - The length of the given 16-bit string set.
    /// * `fs` - The extra space available at the end of SA array (0 should be enough for most cases).
    /// * `freq` - [0..65535] The output 16-bit symbol frequency table (can be NULL).
    ///
    /// # Returns
    ///
    /// 0 if no error occurred, -1 or -2 otherwise.
    pub fn libsais16_gsa_ctx(
        ctx: *const ::std::os::raw::c_void,
        T: *const u16,
        SA: *mut i32,
        n: i32,
        fs: i32,
        freq: *mut i32,
    ) -> i32;

    /// Constructs the suffix array of a given 16-bit string in parallel using OpenMP.
    ///
    /// # Arguments
    ///
    /// * `T` - [0..n-1] The input 16-bit string.
    /// * `SA` - [0..n-1+fs] The output array of suffixes.
    /// * `n` - The length of the given 16-bit string.
    /// * `fs` - The extra space available at the end of SA array (0 should be enough for most cases).
    /// * `freq` - [0..65535] The output 16-bit symbol frequency table (can be NULL).
    /// * `threads` - The number of OpenMP threads to use (can be 0 for OpenMP default).
    ///
    /// # Returns
    ///
    /// 0 if no error occurred, -1 or -2 otherwise.
    #[cfg(feature = "openmp")]
    pub fn libsais16_omp(
        T: *const u16,
        SA: *mut i32,
        n: i32,
        fs: i32,
        freq: *mut i32,
        threads: i32,
    ) -> i32;

    /// Constructs the generalized suffix array (GSA) of given 16-bit string set in parallel using OpenMP.
    ///
    /// # Arguments
    ///
    /// * `T` - [0..n-1] The input 16-bit string set using 0 as separators (T[n-1] must be 0).
    /// * `SA` - [0..n-1+fs] The output array of suffixes.
    /// * `n` - The length of the given 16-bit string set.
    /// * `fs` - The extra space available at the end of SA array (0 should be enough for most cases).
    /// * `freq` - [0..65535] The output 16-bit symbol frequency table (can be NULL).
    /// * `threads` - The number of OpenMP threads to use (can be 0 for OpenMP default).
    ///
    /// # Returns
    ///
    /// 0 if no error occurred, -1 or -2 otherwise.
    #[cfg(feature = "openmp")]
    pub fn libsais16_gsa_omp(
        T: *const u16,
        SA: *mut i32,
        n: i32,
        fs: i32,
        freq: *mut i32,
        threads: i32,
    ) -> i32;

    /// Constructs the suffix array of a given integer array in parallel using OpenMP.Note, during construction input array will be modified, but restored at the end if no errors occurred.
    ///
    /// # Arguments
    ///
    /// * `T` - [0..n-1] The input integer array.
    /// * `SA` - [0..n-1+fs] The output array of suffixes.
    /// * `n` - The length of the integer array.
    /// * `k` - The alphabet size of the input integer array.
    /// * `fs` - Extra space available at the end of SA array (can be 0, but 4k or better 6k is recommended for optimal performance).
    /// * `threads` - The number of OpenMP threads to use (can be 0 for OpenMP default).
    ///
    /// # Returns
    ///
    /// 0 if no error occurred, -1 or -2 otherwise.
    #[cfg(feature = "openmp")]
    pub fn libsais16_int_omp(
        T: *mut i32,
        SA: *mut i32,
        n: i32,
        k: i32,
        fs: i32,
        threads: i32,
    ) -> i32;

    /// Constructs the burrows-wheeler transformed 16-bit string (BWT) of a given 16-bit string.
    ///
    /// # Arguments
    ///
    /// * `T` - [0..n-1] The input 16-bit string.
    /// * `U` - [0..n-1] The output 16-bit string (can be T).
    /// * `A` - [0..n-1+fs] The temporary array.
    /// * `n` - The length of the given 16-bit string.
    /// * `fs` - The extra space available at the end of A array (0 should be enough for most cases).
    /// * `freq` - [0..65535] The output 16-bit symbol frequency table (can be NULL).
    ///
    /// # Returns
    ///
    /// The primary index if no error occurred, -1 or -2 otherwise.
    pub fn libsais16_bwt(
        T: *const u16,
        U: *mut u16,
        A: *mut i32,
        n: i32,
        fs: i32,
        freq: *mut i32,
    ) -> i32;

    /// Constructs the burrows-wheeler transformed 16-bit string (BWT) of a given 16-bit string with auxiliary indexes.
    ///
    /// # Arguments
    ///
    /// * `T` - [0..n-1] The input 16-bit string.
    /// * `U` - [0..n-1] The output 16-bit string (can be T).
    /// * `A` - [0..n-1+fs] The temporary array.
    /// * `n` - The length of the given 16-bit string.
    /// * `fs` - The extra space available at the end of A array (0 should be enough for most cases).
    /// * `freq` - [0..65535] The output 16-bit symbol frequency table (can be NULL).
    /// * `r` - The sampling rate for auxiliary indexes (must be power of 2).
    /// * `I` - [0..(n-1)/r] The output auxiliary indexes.
    ///
    /// # Returns
    ///
    /// 0 if no error occurred, -1 or -2 otherwise.
    pub fn libsais16_bwt_aux(
        T: *const u16,
        U: *mut u16,
        A: *mut i32,
        n: i32,
        fs: i32,
        freq: *mut i32,
        r: i32,
        I: *mut i32,
    ) -> i32;

    /// Constructs the burrows-wheeler transformed 16-bit string (BWT) of a given 16-bit string using libsais16 context.
    ///
    /// # Arguments
    ///
    /// * `ctx` - The libsais16 context.
    /// * `T` - [0..n-1] The input 16-bit string.
    /// * `U` - [0..n-1] The output 16-bit string (can be T).
    /// * `A` - [0..n-1+fs] The temporary array.
    /// * `n` - The length of the given 16-bit string.
    /// * `fs` - The extra space available at the end of A array (0 should be enough for most cases).
    /// * `freq` - [0..65535] The output 16-bit symbol frequency table (can be NULL).
    ///
    /// # Returns
    ///
    /// The primary index if no error occurred, -1 or -2 otherwise.
    pub fn libsais16_bwt_ctx(
        ctx: *const ::std::os::raw::c_void,
        T: *const u16,
        U: *mut u16,
        A: *mut i32,
        n: i32,
        fs: i32,
        freq: *mut i32,
    ) -> i32;

    /// Constructs the burrows-wheeler transformed 16-bit string (BWT) of a given 16-bit string with auxiliary indexes using libsais16 context.
    ///
    /// # Arguments
    ///
    /// * `ctx` - The libsais16 context.
    /// * `T` - [0..n-1] The input 16-bit string.
    /// * `U` - [0..n-1] The output 16-bit string (can be T).
    /// * `A` - [0..n-1+fs] The temporary array.
    /// * `n` - The length of the given 16-bit string.
    /// * `fs` - The extra space available at the end of A array (0 should be enough for most cases).
    /// * `freq` - [0..65535] The output 16-bit symbol frequency table (can be NULL).
    /// * `r` - The sampling rate for auxiliary indexes (must be power of 2).
    /// * `I` - [0..(n-1)/r] The output auxiliary indexes.
    ///
    /// # Returns
    ///
    /// 0 if no error occurred, -1 or -2 otherwise.
    pub fn libsais16_bwt_aux_ctx(
        ctx: *const ::std::os::raw::c_void,
        T: *const u16,
        U: *mut u16,
        A: *mut i32,
        n: i32,
        fs: i32,
        freq: *mut i32,
        r: i32,
        I: *mut i32,
    ) -> i32;

    /// Constructs the burrows-wheeler transformed 16-bit string (BWT) of a given 16-bit string in parallel using OpenMP.
    ///
    /// # Arguments
    ///
    /// * `T` - [0..n-1] The input 16-bit string.
    /// * `U` - [0..n-1] The output 16-bit string (can be T).
    /// * `A` - [0..n-1+fs] The temporary array.
    /// * `n` - The length of the given 16-bit string.
    /// * `fs` - The extra space available at the end of A array (0 should be enough for most cases).
    /// * `freq` - [0..65535] The output 16-bit symbol frequency table (can be NULL).
    /// * `threads` - The number of OpenMP threads to use (can be 0 for OpenMP default).
    ///
    /// # Returns
    ///
    /// The primary index if no error occurred, -1 or -2 otherwise.
    #[cfg(feature = "openmp")]
    pub fn libsais16_bwt_omp(
        T: *const u16,
        U: *mut u16,
        A: *mut i32,
        n: i32,
        fs: i32,
        freq: *mut i32,
        threads: i32,
    ) -> i32;

    /// Constructs the burrows-wheeler transformed 16-bit string (BWT) of a given 16-bit string with auxiliary indexes in parallel using OpenMP.
    ///
    /// # Arguments
    ///
    /// * `T` - [0..n-1] The input 16-bit string.
    /// * `U` - [0..n-1] The output 16-bit string (can be T).
    /// * `A` - [0..n-1+fs] The temporary array.
    /// * `n` - The length of the given 16-bit string.
    /// * `fs` - The extra space available at the end of A array (0 should be enough for most cases).
    /// * `freq` - [0..65535] The output 16-bit symbol frequency table (can be NULL).
    /// * `r` - The sampling rate for auxiliary indexes (must be power of 2).
    /// * `I` - [0..(n-1)/r] The output auxiliary indexes.
    /// * `threads` - The number of OpenMP threads to use (can be 0 for OpenMP default).
    ///
    /// # Returns
    ///
    /// 0 if no error occurred, -1 or -2 otherwise.
    #[cfg(feature = "openmp")]
    pub fn libsais16_bwt_aux_omp(
        T: *const u16,
        U: *mut u16,
        A: *mut i32,
        n: i32,
        fs: i32,
        freq: *mut i32,
        r: i32,
        I: *mut i32,
        threads: i32,
    ) -> i32;

    /// Creates the libsais16 reverse BWT context that allows reusing allocated memory with each libsais16_unbwt_* operation.In multi-threaded environments, use one context per thread for parallel executions.
    ///
    /// # Returns
    ///
    /// the libsais16 context, NULL otherwise.
    pub fn libsais16_unbwt_create_ctx() -> *mut ::std::os::raw::c_void;

    /// Creates the libsais16 reverse BWT context that allows reusing allocated memory with each parallel libsais16_unbwt_* operation using OpenMP.In multi-threaded environments, use one context per thread for parallel executions.
    ///
    /// # Arguments
    ///
    /// * `threads` - The number of OpenMP threads to use (can be 0 for OpenMP default).
    ///
    /// # Returns
    ///
    /// the libsais16 context, NULL otherwise.
    #[cfg(feature = "openmp")]
    pub fn libsais16_unbwt_create_ctx_omp(threads: i32) -> *mut ::std::os::raw::c_void;

    /// Destroys the libsass reverse BWT context and free previusly allocated memory.
    ///
    /// # Arguments
    ///
    /// * `ctx` - The libsais16 context (can be NULL).
    pub fn libsais16_unbwt_free_ctx(ctx: *mut ::std::os::raw::c_void);

    /// Constructs the original 16-bit string from a given burrows-wheeler transformed 16-bit string (BWT) with primary index.
    ///
    /// # Arguments
    ///
    /// * `T` - [0..n-1] The input 16-bit string.
    /// * `U` - [0..n-1] The output 16-bit string (can be T).
    /// * `A` - [0..n] The temporary array (NOTE, temporary array must be n + 1 size).
    /// * `n` - The length of the given 16-bit string.
    /// * `freq` - [0..65535] The input 16-bit symbol frequency table (can be NULL).
    /// * `i` - The primary index.
    ///
    /// # Returns
    ///
    /// 0 if no error occurred, -1 or -2 otherwise.
    pub fn libsais16_unbwt(
        T: *const u16,
        U: *mut u16,
        A: *mut i32,
        n: i32,
        freq: *const i32,
        i: i32,
    ) -> i32;

    /// Constructs the original 16-bit string from a given burrows-wheeler transformed 16-bit string (BWT) with primary index using libsais16 reverse BWT context.
    ///
    /// # Arguments
    ///
    /// * `ctx` - The libsais16 reverse BWT context.
    /// * `T` - [0..n-1] The input 16-bit string.
    /// * `U` - [0..n-1] The output 16-bit string (can be T).
    /// * `A` - [0..n] The temporary array (NOTE, temporary array must be n + 1 size).
    /// * `n` - The length of the given 16-bit string.
    /// * `freq` - [0..65535] The input 16-bit symbol frequency table (can be NULL).
    /// * `i` - The primary index.
    ///
    /// # Returns
    ///
    /// 0 if no error occurred, -1 or -2 otherwise.
    pub fn libsais16_unbwt_ctx(
        ctx: *const ::std::os::raw::c_void,
        T: *const u16,
        U: *mut u16,
        A: *mut i32,
        n: i32,
        freq: *const i32,
        i: i32,
    ) -> i32;

    /// Constructs the original 16-bit string from a given burrows-wheeler transformed 16-bit string (BWT) with auxiliary indexes.
    ///
    /// # Arguments
    ///
    /// * `T` - [0..n-1] The input 16-bit string.
    /// * `U` - [0..n-1] The output 16-bit string (can be T).
    /// * `A` - [0..n] The temporary array (NOTE, temporary array must be n + 1 size).
    /// * `n` - The length of the given 16-bit string.
    /// * `freq` - [0..65535] The input 16-bit symbol frequency table (can be NULL).
    /// * `r` - The sampling rate for auxiliary indexes (must be power of 2).
    /// * `I` - [0..(n-1)/r] The input auxiliary indexes.
    ///
    /// # Returns
    ///
    /// 0 if no error occurred, -1 or -2 otherwise.
    pub fn libsais16_unbwt_aux(
        T: *const u16,
        U: *mut u16,
        A: *mut i32,
        n: i32,
        freq: *const i32,
        r: i32,
        I: *const i32,
    ) -> i32;

    /// Constructs the original 16-bit string from a given burrows-wheeler transformed 16-bit string (BWT) with auxiliary indexes using libsais16 reverse BWT context.
    ///
    /// # Arguments
    ///
    /// * `ctx` - The libsais16 reverse BWT context.
    /// * `T` - [0..n-1] The input 16-bit string.
    /// * `U` - [0..n-1] The output 16-bit string (can be T).
    /// * `A` - [0..n] The temporary array (NOTE, temporary array must be n + 1 size).
    /// * `n` - The length of the given 16-bit string.
    /// * `freq` - [0..65535] The input 16-bit symbol frequency table (can be NULL).
    /// * `r` - The sampling rate for auxiliary indexes (must be power of 2).
    /// * `I` - [0..(n-1)/r] The input auxiliary indexes.
    ///
    /// # Returns
    ///
    /// 0 if no error occurred, -1 or -2 otherwise.
    pub fn libsais16_unbwt_aux_ctx(
        ctx: *const ::std::os::raw::c_void,
        T: *const u16,
        U: *mut u16,
        A: *mut i32,
        n: i32,
        freq: *const i32,
        r: i32,
        I: *const i32,
    ) -> i32;

    /// Constructs the original 16-bit string from a given burrows-wheeler transformed 16-bit string (BWT) with primary index in parallel using OpenMP.
    ///
    /// # Arguments
    ///
    /// * `T` - [0..n-1] The input 16-bit string.
    /// * `U` - [0..n-1] The output 16-bit string (can be T).
    /// * `A` - [0..n] The temporary array (NOTE, temporary array must be n + 1 size).
    /// * `n` - The length of the given 16-bit string.
    /// * `freq` - [0..65535] The input 16-bit symbol frequency table (can be NULL).
    /// * `i` - The primary index.
    /// * `threads` - The number of OpenMP threads to use (can be 0 for OpenMP default).
    ///
    /// # Returns
    ///
    /// 0 if no error occurred, -1 or -2 otherwise.
    #[cfg(feature = "openmp")]
    pub fn libsais16_unbwt_omp(
        T: *const u16,
        U: *mut u16,
        A: *mut i32,
        n: i32,
        freq: *const i32,
        i: i32,
        threads: i32,
    ) -> i32;

    /// Constructs the original 16-bit string from a given burrows-wheeler transformed 16-bit string (BWT) with auxiliary indexes in parallel using OpenMP.
    ///
    /// # Arguments
    ///
    /// * `T` - [0..n-1] The input 16-bit string.
    /// * `U` - [0..n-1] The output 16-bit string (can be T).
    /// * `A` - [0..n] The temporary array (NOTE, temporary array must be n + 1 size).
    /// * `n` - The length of the given 16-bit string.
    /// * `freq` - [0..65535] The input 16-bit symbol frequency table (can be NULL).
    /// * `r` - The sampling rate for auxiliary indexes (must be power of 2).
    /// * `I` - [0..(n-1)/r] The input auxiliary indexes.
    /// * `threads` - The number of OpenMP threads to use (can be 0 for OpenMP default).
    ///
    /// # Returns
    ///
    /// 0 if no error occurred, -1 or -2 otherwise.
    #[cfg(feature = "openmp")]
    pub fn libsais16_unbwt_aux_omp(
        T: *const u16,
        U: *mut u16,
        A: *mut i32,
        n: i32,
        freq: *const i32,
        r: i32,
        I: *const i32,
        threads: i32,
    ) -> i32;

    /// Constructs the permuted longest common prefix array (PLCP) of a given 16-bit string and a suffix array.
    ///
    /// # Arguments
    ///
    /// * `T` - [0..n-1] The input 16-bit string.
    /// * `SA` - [0..n-1] The input suffix array.
    /// * `PLCP` - [0..n-1] The output permuted longest common prefix array.
    /// * `n` - The length of the 16-bit string and the suffix array.
    ///
    /// # Returns
    ///
    /// 0 if no error occurred, -1 otherwise.
    pub fn libsais16_plcp(T: *const u16, SA: *const i32, PLCP: *mut i32, n: i32) -> i32;

    /// Constructs the permuted longest common prefix array (PLCP) of a given 16-bit string set and a generalized suffix array (GSA).
    ///
    /// # Arguments
    ///
    /// * `T` - [0..n-1] The input 16-bit string set using 0 as separators (T[n-1] must be 0).
    /// * `SA` - [0..n-1] The input generalized suffix array.
    /// * `PLCP` - [0..n-1] The output permuted longest common prefix array.
    /// * `n` - The length of the string set and the generalized suffix array.
    ///
    /// # Returns
    ///
    /// 0 if no error occurred, -1 otherwise.
    pub fn libsais16_plcp_gsa(T: *const u16, SA: *const i32, PLCP: *mut i32, n: i32) -> i32;

    /// Constructs the longest common prefix array (LCP) of a given permuted longest common prefix array (PLCP) and a suffix array.
    ///
    /// # Arguments
    ///
    /// * `PLCP` - [0..n-1] The input permuted longest common prefix array.
    /// * `SA` - [0..n-1] The input suffix array or generalized suffix array (GSA).
    /// * `LCP` - [0..n-1] The output longest common prefix array (can be SA).
    /// * `n` - The length of the permuted longest common prefix array and the suffix array.
    ///
    /// # Returns
    ///
    /// 0 if no error occurred, -1 otherwise.
    pub fn libsais16_lcp(PLCP: *const i32, SA: *const i32, LCP: *mut i32, n: i32) -> i32;

    /// Constructs the permuted longest common prefix array (PLCP) of a given 16-bit string and a suffix array in parallel using OpenMP.
    ///
    /// # Arguments
    ///
    /// * `T` - [0..n-1] The input 16-bit string.
    /// * `SA` - [0..n-1] The input suffix array.
    /// * `PLCP` - [0..n-1] The output permuted longest common prefix array.
    /// * `n` - The length of the 16-bit string and the suffix array.
    /// * `threads` - The number of OpenMP threads to use (can be 0 for OpenMP default).
    ///
    /// # Returns
    ///
    /// 0 if no error occurred, -1 otherwise.
    #[cfg(feature = "openmp")]
    pub fn libsais16_plcp_omp(
        T: *const u16,
        SA: *const i32,
        PLCP: *mut i32,
        n: i32,
        threads: i32,
    ) -> i32;

    /// Constructs the permuted longest common prefix array (PLCP) of a given 16-bit string set and a generalized suffix array (GSA) in parallel using OpenMP.
    ///
    /// # Arguments
    ///
    /// * `T` - [0..n-1] The input 16-bit string set using 0 as separators (T[n-1] must be 0).
    /// * `SA` - [0..n-1] The input generalized suffix array.
    /// * `PLCP` - [0..n-1] The output permuted longest common prefix array.
    /// * `n` - The length of the string set and the generalized suffix array.
    /// * `threads` - The number of OpenMP threads to use (can be 0 for OpenMP default).
    ///
    /// # Returns
    ///
    /// 0 if no error occurred, -1 otherwise.
    #[cfg(feature = "openmp")]
    pub fn libsais16_plcp_gsa_omp(
        T: *const u16,
        SA: *const i32,
        PLCP: *mut i32,
        n: i32,
        threads: i32,
    ) -> i32;

    /// Constructs the longest common prefix array (LCP) of a given permuted longest common prefix array (PLCP) and a suffix array in parallel using OpenMP.
    ///
    /// # Arguments
    ///
    /// * `PLCP` - [0..n-1] The input permuted longest common prefix array.
    /// * `SA` - [0..n-1] The input suffix array or generalized suffix array (GSA).
    /// * `LCP` - [0..n-1] The output longest common prefix array (can be SA).
    /// * `n` - The length of the permuted longest common prefix array and the suffix array.
    /// * `threads` - The number of OpenMP threads to use (can be 0 for OpenMP default).
    ///
    /// # Returns
    ///
    /// 0 if no error occurred, -1 otherwise.
    #[cfg(feature = "openmp")]
    pub fn libsais16_lcp_omp(
        PLCP: *const i32,
        SA: *const i32,
        LCP: *mut i32,
        n: i32,
        threads: i32,
    ) -> i32;
}
