name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Test
      run: cargo test --verbose --no-default-features
    - name: Test no OpenMP
      run: cargo test --verbose --no-default-features
    - name: Clippy
      run: cargo clippy --verbose
    - name: Documentation
      run: cargo doc
    - name: Examples
      run: |
        cargo run --example fully_configured_generalized_suffix_array
        cargo run --example large_alphabet_suffix_array
        cargo run --example the_lcp_ladder
        cargo run --example to_the_bwt_and_back
