[package]
name = "libsais-sys"
version = "0.1.0"
edition = "2024"

[features]
default = ["openmp"]
openmp = ["openmp-sys"]

[dependencies]
openmp-sys = { version = "1.2.3", "optional" = true }

[build-dependencies]
cc = "1.2.32"
